name: Build backend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: haskell/actions/setup@v2
        with:
          enable-stack: true
          stack-version: 'latest'
      - uses: actions/cache@v3
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-global-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-global-
      - uses: actions/cache@v3
        name: Cache .stack-work
        with:
          path: .stack-work
          key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('**/*.hs') }}
          restore-keys: |
            ${{ runner.os }}-stack-work-
      - run: stack build
  deploy:
    needs: build
    if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          DEPLOY_WEBHOOK:  ${{secrets.DEPLOY_WEBHOOK}}
        # we ignore any error just fire and forget
        run: curl "$DEPLOY_WEBHOOK"

